# Generated by Django 5.1.3 on 2024-12-11 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adventures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['user', 'adventure'], name='adventures__user_id_1429eb_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['conquered_date'], name='adventures__conquer_a22d58_idx'),
        ),
        migrations.AddConstraint(
            model_name='achievement',
            constraint=models.UniqueConstraint(fields=('user', 'adventure'), name='unique_user_adventure'),
        ),
    ]
