# Generated by Django 5.1.3 on 2025-03-14 10:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0002_initial'),
        ('walks', '0011_adventure_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='adventure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walks.adventure'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='conquered_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Conquered Date'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('FRIENDS', 'Friends Only')], default='PUBLIC', help_text='Control who can see this achievement', max_length=10, verbose_name='Visibility'),
        ),
    ]
