# Generated by Django 5.1.3 on 2025-04-02 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0003_alter_achievement_adventure_and_more'),
        ('walks', '0012_adventure_walks_adv_is_public_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['status'], name='achievements_status_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['visibility'], name='achievements_visibility_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['user', 'status'], name='achievements_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['created_at'], name='achievements_created_at_idx'),
        ),
    ]
