# Generated by Django 5.1.3 on 2024-11-28 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of your epic quest', max_length=200, verbose_name='Title')),
                ('description', models.TextField(help_text="Chronicle your adventure's tale", verbose_name='Description')),
                ('start_date', models.DateField(help_text='When your saga begins', verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='When your tale concludes', verbose_name='End Date')),
                ('difficulty_level', models.CharField(choices=[('NOVICE', 'Novice Quest'), ('APPRENTICE', 'Apprentice Journey'), ('EXPERT', 'Expert Expedition'), ('LEGENDARY', 'Legendary Odyssey')], db_index=True, help_text='Choose your challenge level', max_length=50, verbose_name='Difficulty')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'adventure',
                'verbose_name_plural': 'adventures',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['difficulty_level'], name='walks_adven_difficu_8b632d_idx'), models.Index(fields=['start_date', 'end_date'], name='walks_adven_start_d_d00fee_idx')],
            },
        ),
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='External ID')),
                ('path', models.TextField(help_text='The sacred path of your journey', verbose_name='Path')),
                ('distance', models.FloatField(db_index=True, help_text='Length of your expedition in leagues (km)', verbose_name='Distance')),
                ('elevation_gain', models.FloatField(blank=True, help_text='Height gained during your quest (meters)', null=True, verbose_name='Elevation Gain')),
                ('waypoints', models.JSONField(blank=True, help_text='Ancient scroll containing waypoint coordinates', null=True, verbose_name='Waypoints')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walks', to='walks.adventure', verbose_name='Adventure')),
            ],
            options={
                'verbose_name': 'walk',
                'verbose_name_plural': 'walks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='walks_walk_created_de3203_idx'), models.Index(fields=['distance'], name='walks_walk_distanc_454717_idx')],
            },
        ),
    ]
