# Generated by Django 5.1.3 on 2024-12-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='walk_id',
            field=models.SlugField(help_text="URL-friendly name (e.g. 'caradon-hill-to-trethevy-quoit')", max_length=255, unique=True),
        ),
    ]
