# Generated by Django 5.1.3 on 2024-12-11 18:41

import tagulous.models.fields
import tagulous.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walk',
            name='features',
        ),
        migrations.CreateModel(
            name='WalkFeatureTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('slug',), name='unique_feature_slug')],
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AddField(
            model_name='walk',
            name='features',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Features of this walk', initial='cafe, coastal, historic, pub, wildlife, woodland', space_delimiter=False, to='walks.walkfeaturetag'),
        ),
    ]
