# Generated by Django 5.1.3 on 2024-12-02 17:36

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0002_alter_walk_walk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='description',
            field=tinymce.models.HTMLField(help_text="Chronicle your adventure's tale", verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='highlights',
            field=tinymce.models.HTMLField(default="Details about this walk's highlights to be added.", help_text='Key features and points of interest along the walk', verbose_name='Highlights'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='points_of_interest',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='walk',
            name='rewritten_trail_considerations',
            field=tinymce.models.HTMLField(blank=True, default="Adventurer's Notes:\n- Path suitable for most wanderers\n- Consult local wisdom for seasonal conditions\n- Carry provisions as befits your journey", help_text='Trail considerations rewritten in mystical style', verbose_name='Mystical Trail Notes'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='trail_considerations',
            field=tinymce.models.HTMLField(default='No trail considerations provided.', help_text='Considerations for the trail.'),
        ),
    ]
