# Generated by Django 5.1.3 on 2024-12-11 19:42

import tagulous.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0003_alter_walkfeaturetag_options_alter_walk_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='features',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='walks:feature-autocomplete', blank=True, case_sensitive=False, force_lowercase=True, help_text='Features of this walk', initial='cafe, coastal, historic, pub, wildlife, woodland', protect_initial=True, related_name='walk_set', space_delimiter=False, to='walks.walkfeaturetag'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='related_categories',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Categories related to this walk', related_name='walk_set', space_delimiter=False, to='walks.walkcategorytag'),
        ),
    ]
