# Generated by Django 5.1.3 on 2024-12-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0003_walk_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walkcategorytag',
            options={'verbose_name': 'Walk Category Tag', 'verbose_name_plural': 'Walk Category Tags'},
        ),
        migrations.AlterModelTable(
            name='adventure',
            table='walks_adventure',
        ),
        migrations.AlterModelTable(
            name='walk',
            table='walks_walk',
        ),
        migrations.AlterModelTable(
            name='walkcategorytag',
            table='walks_walkcategorytag',
        ),
    ]
