# Generated by Django 5.1.3 on 2024-12-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0004_alter_walk_features_alter_walk_related_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='walks_by_category', to='walks.walkcategorytag'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='walks_with_feature', to='walks.walkfeaturetag'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='related_categories',
            field=models.ManyToManyField(blank=True, related_name='related_walks', to='walks.walkcategorytag'),
        ),
    ]
