# Generated by Django 5.1.3 on 2024-12-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0005_walk_categories_alter_walk_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='walks', to='walks.walkcategorytag'),
        ),
    ]
