# Generated by Django 5.1.3 on 2024-12-16 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0007_alter_walk_categories_alter_walk_features_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='favorites',
            field=models.ManyToManyField(blank=True, help_text='Users who have favorited this walk', related_name='favorite_walks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WalkFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('walk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walks.walk')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'walk'], name='walks_walkf_user_id_60bf6b_idx'), models.Index(fields=['created_at'], name='walks_walkf_created_29e85c_idx')],
                'unique_together': {('user', 'walk')},
            },
        ),
    ]
