# Generated by Django 5.1.3 on 2024-12-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0008_walk_favorites_walkfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='pubs_list',
            field=models.JSONField(blank=True, default=list, help_text='List of pubs along the walk. Each pub should have a name and optional description.'),
        ),
    ]
