# Generated by Django 5.1.3 on 2025-03-06 15:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0009_alter_walk_pubs_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='end_time',
            field=models.TimeField(blank=True, help_text='When the walk concludes', null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='start_time',
            field=models.TimeField(blank=True, help_text='When the walk begins', null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='difficulty_level',
            field=models.CharField(choices=[('NOVICE WANDERER', 'Novice Wanderer - Beginner'), ("GREY'S PATHFINDER", "Grey's Pathfinder - Beginner to Moderate"), ('TRAIL RANGER', 'Trail Ranger - Moderate'), ("WARDEN'S ASCENT", "Warden's Ascent - Moderate to Challenging"), ('MASTER WAYFARER', 'Master Wayfarer - Challenging')], db_index=True, help_text='Choose your challenge level', max_length=20, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='pubs_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='walk',
            name='steepness_level',
            field=models.CharField(choices=[('NOVICE WANDERER', 'Novice Wanderer - Beginner'), ("GREY'S PATHFINDER", "Grey's Pathfinder - Beginner to Moderate"), ('TRAIL RANGER', 'Trail Ranger - Moderate'), ("WARDEN'S ASCENT", "Warden's Ascent - Moderate to Challenging"), ('MASTER WAYFARER', 'Master Wayfarer - Challenging')], db_index=True, default='NOVICE', help_text='Difficulty level based on steepness', max_length=20, verbose_name='Steepness Level'),
        ),
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of your walking companion', max_length=100, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'companion',
                'verbose_name_plural': 'companions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='adventure',
            name='companions',
            field=models.ManyToManyField(blank=True, help_text='Companions that joined this adventure', related_name='adventures', to='walks.companion'),
        ),
        migrations.AddIndex(
            model_name='companion',
            index=models.Index(fields=['user'], name='walks_compa_user_id_8973e1_idx'),
        ),
        migrations.AddIndex(
            model_name='companion',
            index=models.Index(fields=['created_at'], name='walks_compa_created_b8ab2d_idx'),
        ),
    ]
