# Generated by Django 5.1.3 on 2025-03-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0010_adventure_end_time_adventure_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether this adventure is visible to other users', verbose_name='Public'),
        ),
    ]
