# Generated by Django 5.2.17 on 2026-09-26 12:00

import django.db.models.deletion
import walkquest.walks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walks", "0012_adventure_walks_adv_is_public_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="walk",
            name="photo_source_url",
            field=models.URLField(
                blank=True,
                help_text="Page the walk's photos were imported from (credited in the UI)",
                max_length=500,
                verbose_name="Photo source page",
            ),
        ),
        migrations.AlterField(
            model_name="walk",
            name="distance",
            field=models.FloatField(
                default=0.0, help_text="Distance of the walk in miles."
            ),
        ),
        migrations.CreateModel(
            name="WalkPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("is_main", models.BooleanField(db_index=True, default=False)),
                (
                    "source_url",
                    models.URLField(
                        help_text="Original image URL the photo was imported from",
                        max_length=500,
                    ),
                ),
                ("caption", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Large WebP rendition (max 960px wide)",
                        upload_to=walkquest.walks.models.walk_photo_upload_to,
                    ),
                ),
                (
                    "thumb",
                    models.ImageField(
                        blank=True,
                        help_text="Small WebP rendition for lists (max 320px wide)",
                        upload_to=walkquest.walks.models.walk_photo_upload_to,
                    ),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "credit",
                    models.CharField(
                        blank=True, default="iWalk Cornwall", max_length=255
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                (
                    "walk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="walks.walk",
                    ),
                ),
            ],
            options={
                "verbose_name": "walk photo",
                "verbose_name_plural": "walk photos",
                "ordering": ["-is_main", "position"],
                "indexes": [
                    models.Index(
                        fields=["walk", "is_main", "position"],
                        name="walks_photo_order_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("walk", "source_url"), name="unique_walk_photo_source"
                    )
                ],
            },
        ),
    ]
