# Generated by Django 5.2.17 on 2026-09-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0013_walk_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='transport_info',
            field=models.JSONField(blank=True, default=dict, help_text='Nearest bus stops and lines, from NaPTAN/TransportAPI (see transport.py)', verbose_name='Public transport'),
        ),
    ]
