# Generated by Django 5.2.17 on 2026-09-29 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0015_schedule_transport_refresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='walk',
            field=models.ForeignKey(blank=True, help_text='The walk this log entry is about (unset on catalogue rows)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='walks.walk'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='adventure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walks', to='walks.adventure'),
        ),
    ]
