# Generated by Django 5.1.3 on 2024-11-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='experience_points',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Experience Points'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Active'),
        ),
        migrations.AddField(
            model_name='user',
            name='quests_completed',
            field=models.PositiveIntegerField(default=0, verbose_name='Completed Quests'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Name of User'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_user_usernam_65d164_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['experience_points'], name='users_user_experie_b7d921_idx'),
        ),
    ]
